#!/bin/bash

if [ -d "/$1" ]; then
  echo "$(hostname).$(domainname)   /$1"
  ls -l /$1
  printf "\n"
  cd /$1
else
  echo "/$1 does not exist"
  echo "create directory? y/n"
  read copyflag
  if [ "$copyflag" = "y" ]
  then
    mkdir -m 777 /$1
    echo "$(hostname).$(domainname):  /$1"
    ls -l /$1
    printf "\n"
  fi
fi
